package hive;

public enum RequestType {
	CREATE_USER,
	INSERT_COMMENT,
	INSERT_POST,
	GET_ALL_POST_COMMENTS,
	GET_ALL_POSTS_AROUND_USER,
	GET_ALL_POSTS_BY_USER,
	GET_ALL_POSTS_COMMENTED_ON_BY_USER,
	UPDATE_POST
}
